version: '3.9'
services:
  mssql:
    container_name: mssql-db
    hostname: mssql-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_USER: 'SA'
      MSSQL_SA_PASSWORD: 'Passw0rd123'
      MSSQL_DATA_DIR: /var/opt/mssql/data
      MSSQL_PID: 'Developer'
      MSSQL_TCP_PORT: 1433
    ports:
      - 1433:1433
  # app:
  #     environment:
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     image: 'docker_img/dw_dev:v0.0.4' #change the number version to create new images
  #     build: .
  #     ports:
  #     - 8080:8080
